app/routes/menu.py
"""
Module for transaction menu
"""

from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_babelex import _
from flask_modals import render_template_modal
from flask_security import login_required, roles_accepted

from app import db
from app.business_logic import TransactionHandler
from app.forms import (ByWeightForm, CoffeeShopForm, ExpanseForm, SupplyForm,
                       WriteOffForm)
from app.models import Barista, Shop, ShopEquipment, Storage

menu = Blueprint("menu", __name__, url_prefix="/menu")


@menu.route("/expense", methods=("POST",))
@login_required
def expense():
    """Expanse transaction form"""
    form = ExpanseForm()
    transaction = TransactionHandler(form.coffee_shop.data)
    if form.validate_on_submit():
        if transaction.is_report_send(form.coffee_shop.data):
            flash(_("Сегодняшний отчет уже был отправлен!"))
        else:
            transaction.create_expense(form)
            flash(_("Транзакция принята!"))
        return redirect(url_for("home"))
    flash(_("Транзакция не принята!  Попробуйте заново, с коректными значениями."))
    return render_template_modal("index.html", modal="modal-form")


@menu.route(
    "/by_weight",
    methods=[
        "POST",
    ],
)
@login_required
def by_weight():
    """By weight transaction form"""
    form = ByWeightForm(request.form)
    transaction = TransactionHandler(form.coffee_shop.data)
    if form.validate_on_submit():
        if transaction.is_report_send(form.coffee_shop.data):
            flash(_("Сегодняшний отчет уже был отправлен!"))
        else:
            transaction.crete_by_weight(form)
            flash(_("Транзакция принята!"))
        return redirect(url_for("home"))
    flash(_("Транзакция не принята!  Попробуйте заново, с коректными значениями."))
    return render_template_modal("index.html", modal="modal-form")


@menu.route("/write_off", methods=("POST",))
@login_required
def write_off():
    """Write off transaction form"""
    form = WriteOffForm(request.form)
    transaction = TransactionHandler(form.coffee_shop.data)
    if form.validate_on_submit():
        if transaction.is_report_send(form.coffee_shop.data):
            flash(_("Сегодняшний отчет уже был отправлен!"))
        else:
            transaction.create_write_off(form)
            flash(_("Транзакция принята!"))
        return redirect(url_for("home"))
    flash(_("Транзакция не принята!  Попробуйте заново, с коректными значениями."))
    return render_template_modal("index.html", modal="modal-form")


@menu.route("/supply", methods=("POST",))
@login_required
def supply():
    """Supply off transaction form"""
    form = SupplyForm(request.form)
    transaction = TransactionHandler(form.coffee_shop.data)
    if form.validate_on_submit():
        if transaction.is_report_send(form.coffee_shop.data):
            flash(_("Сегодняшний отчет уже был отправлен!"))
        else:
            transaction.create_supply(form)
            flash(_("Транзакция принята!"))
        return redirect(url_for("home"))
    flash(_("Транзакция не принята!  Попробуйте заново, с коректными значениями."))
    return render_template_modal("index.html", modal="modal-form")


@menu.route("/create_coffee_shop", methods=("GET", "POST"))
@login_required
@roles_accepted("admin", "moderator")
def create_coffee_shop():
    """Create coffee shop form"""
    form = CoffeeShopForm()
    if form.validate_on_submit():
        shop = Shop(
            place_name=form.place_name.data,
            address=form.address.data,
            timestamp=datetime.utcnow(),
            cash=form.cash.data,
            cashless=form.cashless.data,
        )
        storage = Storage(
            coffee_arabika=form.coffee_arabika.data,
            coffee_blend=form.coffee_blend.data,
            milk=form.milk.data,
            panini=form.panini.data,
            sausages=form.sausages.data,
            buns=form.buns.data,
        )
        equipment = ShopEquipment(
            coffee_machine=form.coffee_machine.data,
            grinder_1=form.grinder_1.data,
            grinder_2=form.grinder_2.data,
        )
        shop.shop_equipment = equipment
        shop.storage = storage
        for staff_id in form.staff_list.data:
            staff = Barista.query.filter_by(id=staff_id).first_or_404()
            shop.baristas.append(staff)
        db.session.add(storage)
        db.session.add(equipment)
        db.session.add(shop)
        db.session.commit()
        flash(_("Создана новая кофейня!"))
        return redirect(url_for("home"))
    return render_template("menu/new_coffee_shop.html", form=form)

app/routes/report.py
"""
Module for report form
"""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_babelex import _
from flask_security import current_user, login_required

from app import app, date_today
from app.business_logic import TransactionHandler
from app.forms import ReportForm
from app.models import (ByWeight, Category, CollectionFund, DepositFund,
                        Expense, Report, Shop, Storage, Supply,
                        TransferProduct)

report = Blueprint("reports", __name__, url_prefix="/report")


@report.route("/create", methods=["GET", "POST"])
@login_required
def create():
    """Create report form"""
    form = ReportForm(request.form)
    find_salary_exp = Expense.query.select_from(Category)
    find_salary_exp = find_salary_exp.filter(Category.name == "Зарплата")
    find_salary_exp = find_salary_exp.filter(Expense.timestamp >= date_today).first()
    if not find_salary_exp:
        flash(_("Возьмите зарплату за сегодняшний день!"))
    if form.validate_on_submit():
        transaction = TransactionHandler(form.shop.data)

        if transaction.is_report_send(form.shop.data):
            flash(_("Сегодняшний отчет уже был отправлен!"))
        else:
            transaction.create_report(form)
            flash(_("Отчет за день отправлен!"))
        return redirect(url_for("home"))
    return render_template(
        "report/create_report.html", title="Создание отчёта", form=form
    )


@report.route("/<shop_address>")
@login_required
def on_address(shop_address):
    """Render all reports with pagination"""
    shop = Shop.query.filter_by(address=shop_address).first_or_404()
    storage = Storage.query.filter_by(shop_id=shop.id).first_or_404()
    reports = Report.query.filter_by(shop_id=shop.id).order_by(Report.timestamp.desc())
    if not (current_user.has_role("admin") or current_user.has_role("moderator")):
        reports = reports.limit(app.config["REPORTS_USER_VIEW"]).from_self()

    global_expense = Expense.get_global(shop.id)
    local_expense = Expense.get_local(shop.id)
    supply = Supply.get_local(storage.id, False)
    by_weight = ByWeight.get_local(storage.id, False)
    deposit_fund = DepositFund.get_local_by_shop(shop.id, False)
    collection_fund = CollectionFund.get_local_by_shop(shop.id, False)
    transfer = TransferProduct
    page = request.args.get("page", 1, type=int)
    reports = reports.paginate(page, app.config["REPORTS_PER_PAGE"], False)
    next_url = (
        url_for("reports.on_address", shop_address=shop.address, page=reports.next_num)
        if reports.has_next
        else None
    )
    prev_url = (
        url_for("reports.on_address", shop_address=shop.address, page=reports.prev_num)
        if reports.has_prev
        else None
    )
    return render_template(
        "report/reports.html",
        daily_reports=reports.items,
        global_expense=global_expense,
        local_expense=local_expense,
        deposit_fund=deposit_fund,
        collection_fund=collection_fund,
        transfer=transfer,
        supply=supply,
        by_weight=by_weight,
        next_url=next_url,
        prev_url=prev_url,
    )

app/templates/menu/_by_weight_modal.html
<div class="modal fade" id="ByWeightModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="ByWeightModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            {{ modal_messages() }}
            <form action="{{ url_for('menu.by_weight') }}" method="post">
            {{ by_weight_form.csrf_token }}
            <div class="modal-header">
                <h5 class="modal-title" id="ByWeightModalLabel">{{_('Продажа развеса')}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ render_select_field(by_weight_form.coffee_shop) }}
                <p>{{ by_weight_form.by_weight_choice.label }}{{ by_weight_form.by_weight_choice(class="form-select") }}</p>
                {{ render_field(by_weight_form.amount) }}
                <p>{{ by_weight_form.type_cost.label }} {{ by_weight_form.type_cost(class="form-check") }}</p>
                {{ render_field(by_weight_form.money) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Закрыть')}}</button>
                {{ by_weight_form.submit(class="btn btn-primary") }}
            </div>
            </form>
        </div>
    </div>
</div>

app/templates/menu/_consumption_modal.html
<div class="modal fade" id="ConsumptionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="ConsumptionModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            {{ modal_messages() }}
            <form action="{{ url_for('menu.expense') }}" method="post">
            {{ expense_form.csrf_token }}
            <div class="modal-header">
                <h5 class="modal-title" id="ConsumptionModal">Расход</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    {{ expense_form.coffee_shop.label }}
                    {{ expense_form.coffee_shop(class="form-select mb-3") }}
                </div>
                <div class="form-floating mb-3">
                </div>
                <div class="mb-3 form-check">
                    {{ expense_form.is_global(class="form-check-input") }}
                    {{ expense_form.is_global.label(class="form-check-label") }}
                </div>
                <div class="form-check">
                {% for radio in expense_form.type_cost %}
                   {{ radio.label}} {{ radio }}
                {% endfor %}
                </div>
                {{ render_field(expense_form.money) }}
                {{expense_form.categories.label}}
                {{ expense_form.categories(class="form-select") }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                {{ expense_form.submit(class="btn btn-primary") }}
            </div>
            </form>
        </div>
    </div>
</div>

app/templates/menu/_expense_modal.html
<div class="modal fade" id="ConsumptionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="ConsumptionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            {{ modal_messages() }}
            <form action="{{ url_for('menu.expense') }}" method="post">
            {{ expense_form.csrf_token }}
            <div class="modal-header">
                <h5 class="modal-title" id="ConsumptionModalLabel">{{_('Расход')}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ render_select_field(expense_form.coffee_shop) }}
                <div class="form-floating mb-3">
                </div>
                <div class="mb-3 form-check">
                    {{ expense_form.is_global(class="form-check-input") }}
                    {{ expense_form.is_global.label(class="form-check-label") }}
                </div>
                <div class="form-check">
                {% for radio in expense_form.type_cost %}
                   {{ radio.label }} {{ radio }}
                {% endfor %}
                </div>
                {{ render_field(expense_form.money) }}
                {{ render_select_field(expense_form.categories) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Закрыть')}}</button>
                {{ expense_form.submit(class="btn btn-primary") }}
            </div>
            </form>
        </div>
    </div>
</div>

app/templates/menu/_supply_modal.html
<div class="modal fade" id="SupplyModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="SupplyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            {{ modal_messages() }}
            <form action="{{ url_for('menu.supply') }}" method="post">
            {{ supply_form.csrf_token }}
            <div class="modal-header">
                <h5 class="modal-title" id="SupplyModalLabel">{{_('Поступление')}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ render_select_field(supply_form.coffee_shop) }}
                {{ render_select_field(supply_form.supply_choice) }}
                {{ render_field(supply_form.amount) }}
                <p>{{ supply_form.type_cost.label }} {{ supply_form.type_cost(class="form-check") }}</p>
                {{ render_field(supply_form.money) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Закрыть')}}</button>
                {{ supply_form.submit(class="btn btn-primary") }}
            </div>
            </form>
        </div>
    </div>
</div>

app/templates/menu/_user_menu.html
<div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.profile', user_name=current_user.name) }}">{{_('Мой профиль')}}</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('reports.create') }}">{{_('Создание отчёта')}}</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ _('Транзакции') }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li>
                      <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#ConsumptionModal">{{ _('Расход') }}</a>
                  </li>
                  <li>
                    <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#SupplyModal">{{ _('Поступление') }}</a>
                  </li>
                  <li>
                      <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#ByWeightModal">{{ _('Продажа развеса') }}</a>
                  </li>
                  <li>
                      <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#WriteOffModal">{{ _('Списание') }}</a>
                  </li>
              </ul>
          </li>
          {% if current_user.has_role('admin') or current_user.has_role('moderator') %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.index') }}">{{ _('Администрирование') }}</a>
          </li>
          {% endif %}
          {% if current_user.has_role('admin') %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('menu.create_coffee_shop') }}">{{ _('Создать Кофейню') }}</a>
              <a class="nav-link" href="{{ url_for('create_new_staff') }}">{{ _('Добавить сотрудника') }}</a>
          </li>
          {% endif %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('logout') }}">{{ _('Выход') }}</a>
          </li>
    </ul>
</div>

app/templates/menu/_write_off_modal.html
<div class="modal fade" id="WriteOffModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="WriteOffModalLabel" aria-hidden="true">\
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            {{ modal_messages() }}
            <form action="{{ url_for('menu.write_off') }}" method="post">
            {{ write_off_form.csrf_token }}
            <div class="modal-header">
                <h5 class="modal-title" id="WriteOffModalLabel">{{ _('Списание') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ render_select_field(write_off_form.coffee_shop) }}
                {{ render_select_field(write_off_form.write_off_choice) }}
                {{ render_field(supply_form.amount) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Закрыть') }}</button>
                {{ write_off_form.submit(class="btn btn-primary") }}
            </div>
            </form>
        </div>
    </div>
</div>

app/templates/menu/new_coffee_shop.html
{% extends "base.html" %}
{% block title %}{{ _('Создание новой кофейни') }}{% endblock %}
{% block content %}
<h1>{{ _('Создание кофейни') }}</h1>
    <form method="post">
      {{ form.csrf_token }}
      {{ render_field(form.place_name) }}
      {{ render_field(form.address) }}
      {{ render_field(form.cash) }}
      {{ render_field(form.cashless) }}
      <h4>{{ _('Оборудование') }}</h4>
      {{ render_field(form.coffee_machine) }}
      {{ render_field(form.grinder_1) }}
      {{ render_field(form.grinder_2) }}
      <h4>{{ _('Склад') }}</h4>
      {{ render_field(form.milk) }}
      {{ render_field(form.coffee_blend) }}
      {{ render_field(form.coffee_arabika) }}
      {{ render_field(form.panini) }}
      {{ render_field(form.sausages) }}
      {{ render_field(form.buns) }}
      <br/>
      {{ render_select_field(form.staff_list) }}
      <p>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</p>
    </form>
{% endblock %}