app/routes/user.py
"""
Module contains user edit view form
and change password view
"""


from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_babelex import _
from flask_security import current_user, login_required

from app import db
from app.forms import EditProfileForm, NewPassword
from app.models import Barista

user = Blueprint("user", __name__, url_prefix="/user")


@user.route("/<user_name>")
@login_required
def profile(user_name):
    """Query user by 'user_name' and render on template"""
    user_obj = Barista.query.filter_by(name=user_name).first_or_404()
    return render_template("user/user.html", user=user_obj)


@user.route("/edit_profile", methods=("GET", "POST"))
@login_required
def edit():
    """Edit user form template"""
    form = EditProfileForm(
        current_user.name, current_user.phone_number, current_user.email
    )
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.phone_number = form.phone_number.data
        current_user.email = form.email.data
        db.session.commit()
        flash(_("Ваши изменения сохранены."))
        return redirect(url_for("user.profile", user_name=current_user))
    if request.method == "GET":
        form.name.data = current_user.name
        form.phone_number.data = current_user.phone_number
        form.email.data = current_user.email
    return render_template("user/user_edit.html", user=current_user, form=form)


@user.route("/new_password", methods=("POST", "GET"))
@login_required
def change_password():
    """Change password template view"""
    form = NewPassword()
    if form.validate_on_submit():
        current_user.password = form.password.data
        db.session.commit()
        flash(_("Ваши изменения сохранены."))
        return redirect(url_for("user.profile", user_name=current_user))
    return render_template("user/user_password.html", user=current_user, form=form)

app/templates/user/user.html
{% extends "base.html" %}
{% block title %}{{_('Профиль')}} {{user.name}}{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <h4>{{_('Имя')}}: {{ user.name }}</h4>
        <h4>{{_('Тел.')}}: {{ user.phone_number }}</h4>
        <h4>{{_('Емейл')}}: {{ user.email }}</h4>
        <h4>{{_('Место работы')}}:</h4>
        <ul>
            {% for s in user.shop %}
                <li>{{s.place_name}} / {{ s.address}}</li>
            {% endfor %}
        </ul>
        <h4>{{_('Роли')}}:</h4>
        <ul>
            {% for role in user.roles %}
                <li>{{role.name}}</li>
            {% endfor %}
        </ul>
        {% if current_user == user %}
            <a href="{{ url_for('user.edit') }} ">{{_('Редактировать профиль')}}</a>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/user/user_edit.html
{% extends "base.html" %}
{% block title %}{{_('Профиль')}} {{user.name}}{% endblock %}
{% block style %}
.form-floating:focus-within {
  z-index: 2;
}
.bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
{% endblock %}
{% block content %}
<h1>Редактирование профиля</h1>
<form method="post">
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_phone_field(form.phone_number) }}
    {{ render_field(form.email) }}
    <p>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</p>
</form>
{% endblock %}

app/templates/user/user_password.html
{% extends "base.html" %}
{% block title %}{{_('Профиль')}} {{user.name}}{% endblock %}
{% block style %}
.form-floating:focus-within {
  z-index: 2;
}
.bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
{% endblock %}
{% block content %}
<h1>{{_('Изменение пароля')}}</h1>
<form method="post">
    {{ form.csrf_token }}
    {{ render_password_field(form.password) }}
    {{ render_password_field(form.password2) }}
    <p>{{ form.submit(class="w-100 btn btn-lg btn-primary") }}</p>
</form>
{% endblock %}